- name: "Read ENV specific variables {{ env }}_vars.yml"
  include_vars:
    file: "{{ env }}_vars.yml"

- name: "Read AWS credenatials vault {{ env }}_vars.yml"
  include_vars:
    file: "{{ local_private_repo_location }}/aws-credenatials/aws-credenatials.yml"

- name: "Create {{ env }} stack"
  cloudformation:

    # /home/setevoy/Work/RTFM/Bitbucket/rtfm-infrastructure/aws-credenatials/aws-credenatials.yml
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"

    # aws_env - from hosts.ini
    stack_name: "{{ aws_env }}"
    state: "present"
    disable_rollback: true
    template: "roles/cloudformation/files/rtfm-cf-stack.json"

    # roles/cloudformation/vars/main.yml
    region: "{{ region }}"

    template_parameters:

      # roles/cloudformation/vars/main.yml
      AMIID: "{{ ami_id }}"
      AvailabilityZone: "{{ availability_zone }}"
      OfficeAllowLocation: "{{ office_allow_location }}"
      HomeAllowLocationProvider1: "{{ home_allow_location_provider1 }}"
      HomeAllowLocationProvider2: "{{ home_allow_location_provider2 }}"
      
      # roles/cloudformation/vars/dev_vars.yml
      ENV: "{{ aws_env }}"
      KeyName: "{{ key_name }}"
      EC2InstanceType: "{{ ec2_instance_type }}"
      DataEBSID: "{{ data_ebs_id }}"
      BackupsEBSID: "{{ backups_ebs_id }}"
    tags:
      Stack: "{{ aws_env }}"
